from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ff5f6a4f80'
down_revision = '4bc91857039a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Fix admins tables
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_admins_user_id', 'users', ['user_id'], ['id'])
        batch_op.drop_column('admin_id')  # Drop the old admin_id column if it's no longer needed


    # Fix products table
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # Fix sales table
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_sales_seller_id', 'users', ['seller_id'], ['id'])  # Provide a name for the foreign key

    # Fix users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Revert users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # Revert sales table
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sales_seller_id', type_='foreignkey')  # Drop the foreign key by its name
        batch_op.drop_column('seller_id')

    # Revert products table
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=200), nullable=True))

    # Revert admins table
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_admins_user_id', type_='foreignkey')  # Drop the foreign key by its name
        batch_op.create_foreign_key('fk_admins_admin_id', 'users', ['admin_id'], ['id'])  # Recreate the original constraint
        batch_op.drop_column('user_id')

    # ### end Alembic commands ### 
