"""Add image_url column to products table

Revision ID: 083ba2ae2b69
Revises: 815938b77877
Create Date: 2024-11-12 21:51:38.271393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083ba2ae2b69'
down_revision = '815938b77877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
