"""Add gender field to User model

Revision ID: 582e21848491
Revises: 41ae74eecc92
Create Date: 2024-11-12 04:36:27.340951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582e21848491'
down_revision = '41ae74eecc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
