"""Added profile_image to User model

Revision ID: 815938b77877
Revises: 582e21848491
Create Date: 2024-11-12 06:06:29.527391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815938b77877'
down_revision = '582e21848491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
